export const BALANCED_SUBSET_DECISION_STATUS_SELECTED = `SELECTED`;
export const BALANCED_SUBSET_DECISION_STATUS_SKIPPED = `SKIPPED`;

export const BALANCED_SUBSET_DECISION_STATUSES = [
  BALANCED_SUBSET_DECISION_STATUS_SELECTED,
  BALANCED_SUBSET_DECISION_STATUS_SKIPPED,
] as const;

export const BALANCED_SUBSET_REASON_SELECTED = `SELECTED`;
export const BALANCED_SUBSET_REASON_HARD_REJECTED = `HARD_REJECTED`;
export const BALANCED_SUBSET_REASON_BUCKET_TARGET_FILLED = `BUCKET_TARGET_FILLED`;
export const BALANCED_SUBSET_REASON_BUCKET_TARGET_MISSING = `BUCKET_TARGET_MISSING`;
export const BALANCED_SUBSET_REASON_SUBSET_TARGET_FILLED = `SUBSET_TARGET_FILLED`;

export const BALANCED_SUBSET_REASON_CODES = [
  BALANCED_SUBSET_REASON_SELECTED,
  BALANCED_SUBSET_REASON_HARD_REJECTED,
  BALANCED_SUBSET_REASON_BUCKET_TARGET_FILLED,
  BALANCED_SUBSET_REASON_BUCKET_TARGET_MISSING,
  BALANCED_SUBSET_REASON_SUBSET_TARGET_FILLED,
] as const;
