export const HEALTH_STATUS_OK = `OK`;
export const HEALTH_STATUS_DEGRADED = `DEGRADED`;
export const HEALTH_STATUS_DOWN = `DOWN`;
export const HEALTH_STATUSES = [
  HEALTH_STATUS_OK,
  HEALTH_STATUS_DEGRADED,
  HEALTH_STATUS_DOWN,
] as const;
