export const INFORMAL_WRITING_SIGNAL_CASUAL_PUNCTUATION = `CASUAL_PUNCTUATION`;
export const INFORMAL_WRITING_SIGNAL_CASUAL_WORD = `CASUAL_WORD`;
export const INFORMAL_WRITING_SIGNAL_CONTRACTION = `CONTRACTION`;
export const INFORMAL_WRITING_SIGNAL_EMOTICON = `EMOTICON`;
export const INFORMAL_WRITING_SIGNAL_OFFENSIVE_LANGUAGE = `OFFENSIVE_LANGUAGE`;
export const INFORMAL_WRITING_SIGNAL_PLATFORM_CHAT_TERM = `PLATFORM_CHAT_TERM`;
export const INFORMAL_WRITING_SIGNAL_REPEATED_LETTERS = `REPEATED_LETTERS`;
export const INFORMAL_WRITING_SIGNAL_SOCIAL_SLANG = `SOCIAL_SLANG`;
export const INFORMAL_WRITING_SIGNAL_TEXTING_ACRONYM = `TEXTING_ACRONYM`;

export const INFORMAL_WRITING_SIGNALS = [
  INFORMAL_WRITING_SIGNAL_CASUAL_PUNCTUATION,
  INFORMAL_WRITING_SIGNAL_CASUAL_WORD,
  INFORMAL_WRITING_SIGNAL_CONTRACTION,
  INFORMAL_WRITING_SIGNAL_EMOTICON,
  INFORMAL_WRITING_SIGNAL_OFFENSIVE_LANGUAGE,
  INFORMAL_WRITING_SIGNAL_PLATFORM_CHAT_TERM,
  INFORMAL_WRITING_SIGNAL_REPEATED_LETTERS,
  INFORMAL_WRITING_SIGNAL_SOCIAL_SLANG,
  INFORMAL_WRITING_SIGNAL_TEXTING_ACRONYM,
] as const;

/*
 * Monorepo-owned informal writing terms. Source categories consulted on
 * 2026-06-06: Merriam-Webster Slang & Trending, Dictionary.com Slang,
 * Cambridge Dictionary updates, NetLingo chat acronym references, Pew
 * teen/social media context, and Wiktionary internet/texting slang categories
 * as license-aware cross-checks. These are manually curated category samples,
 * not copied third-party dictionaries or tables.
 */
export const INFORMAL_WRITING_CASUAL_TERMS = [
  `aight`,
  `ain't`,
  `alrighty`,
  `anyhoo`,
  `anywho`,
  `bae`,
  `bestie`,
  `bro`,
  `cmon`,
  `coz`,
  `cuz`,
  `dunno`,
  `dude`,
  `gimme`,
  `gonna`,
  `gotta`,
  `gotcha`,
  `haha`,
  `hehe`,
  `hey`,
  `heya`,
  `homie`,
  `howdy`,
  `ima`,
  `imma`,
  `k`,
  `kinda`,
  `kk`,
  `lemme`,
  `lolz`,
  `meh`,
  `nah`,
  `naw`,
  `nope`,
  `okie`,
  `okies`,
  `outta`,
  `pls`,
  `plz`,
  `prolly`,
  `sorta`,
  `sup`,
  `thx`,
  `tho`,
  `tryna`,
  `ty`,
  `tysm`,
  `u`,
  `ugh`,
  `ur`,
  `wanna`,
  `wassup`,
  `whatevs`,
  `welp`,
  `whatcha`,
  `wut`,
  `ya`,
  `y'all`,
  `yall`,
  `yea`,
  `yeah`,
  `yep`,
  `yo`,
  `yup`,
] as const;

export const INFORMAL_WRITING_TEXTING_ACRONYMS = [
  `af`,
  `afaik`,
  `afaict`,
  `afk`,
  `atm`,
  `bbl`,
  `bff`,
  `bffr`,
  `brb`,
  `btw`,
  `dae`,
  `eli5`,
  `fomo`,
  `ftw`,
  `fyi`,
  `fwiw`,
  `g2g`,
  `gtg`,
  `hbu`,
  `hmu`,
  `hth`,
  `icymi`,
  `idc`,
  `idk`,
  `ikr`,
  `ily`,
  `ilym`,
  `ilysm`,
  `imho`,
  `imo`,
  `irl`,
  `iirc`,
  `istg`,
  `jk`,
  `jkjk`,
  `lfg`,
  `lmao`,
  `lmfao`,
  `lmk`,
  `lol`,
  `mfw`,
  `ngl`,
  `np`,
  `nvm`,
  `ofc`,
  `omg`,
  `ong`,
  `omw`,
  `ootd`,
  `pov`,
  `rn`,
  `rofl`,
  `rotfl`,
  `smh`,
  `srsly`,
  `sry`,
  `stg`,
  `tbf`,
  `tbh`,
  `tfw`,
  `til`,
  `tldr`,
  `tmi`,
  `ttyl`,
  `wbu`,
  `wdym`,
  `wtf`,
  `wth`,
  `wyd`,
  `wym`,
  `wya`,
  `ykwim`,
  `yolo`,
  `yw`,
] as const;

export const INFORMAL_WRITING_SOCIAL_SLANG_TERMS = [
  `ate`,
  `ate and left no crumbs`,
  `aura`,
  `aura farming`,
  `aura points`,
  `baddie`,
  `based`,
  `bet`,
  `big mood`,
  `brain rot`,
  `brainrot`,
  `brat`,
  `bruh`,
  `bussin`,
  `canon event`,
  `cap`,
  `caught lacking`,
  `chalked`,
  `cheugy`,
  `clapback`,
  `clout`,
  `cooked`,
  `cringe`,
  `cringey`,
  `deadass`,
  `ded`,
  `delulu`,
  `dope`,
  `drip`,
  `era`,
  `extra`,
  `fam`,
  `fanum tax`,
  `finna`,
  `fire`,
  `fit check`,
  `flex`,
  `fr`,
  `glaze`,
  `glazing`,
  `glow up`,
  `glowup`,
  `goated`,
  `gyatt`,
  `high key`,
  `highkey`,
  `hit different`,
  `hits different`,
  `ick`,
  `it's giving`,
  `its giving`,
  `iykyk`,
  `left no crumbs`,
  `let him cook`,
  `lit`,
  `looksmaxxing`,
  `lowkey`,
  `main character`,
  `main character energy`,
  `mewing`,
  `mid`,
  `mood`,
  `mog`,
  `mogging`,
  `no cap`,
  `ohio`,
  `ok boomer`,
  `on god`,
  `opp`,
  `opps`,
  `out of pocket`,
  `periodt`,
  `pookie`,
  `pressed`,
  `rizz`,
  `rizzed`,
  `rizzing`,
  `rizzler`,
  `salty`,
  `savage`,
  `say less`,
  `sheesh`,
  `sigma`,
  `skibidi`,
  `sksksk`,
  `situationship`,
  `simp`,
  `slaps`,
  `slay`,
  `snatched`,
  `sus`,
  `sussy`,
  `tea`,
  `touch grass`,
  `valid`,
  `vibe`,
  `vibe check`,
  `vibes`,
  `vibing`,
  `yass`,
  `yeet`,
] as const;

export const INFORMAL_WRITING_PLATFORM_CHAT_TERMS = [
  `ama`,
  `copypasta`,
  `dm`,
  `duet`,
  `finsta`,
  `fyp`,
  `gg`,
  `ggs`,
  `ggwp`,
  `glhf`,
  `grwm`,
  `hashtag`,
  `livestream`,
  `meme`,
  `moots`,
  `mutual`,
  `npc`,
  `oomf`,
  `op`,
  `pfp`,
  `pm`,
  `pog`,
  `poggers`,
  `qotd`,
  `quote tweet`,
  `ratio`,
  `ratioed`,
  `reply guy`,
  `repost`,
  `retweet`,
  `rt`,
  `shadowban`,
  `ship`,
  `shipping`,
  `stan`,
  `stitch`,
  `streamer`,
  `subreddit`,
  `subtweet`,
  `thread`,
  `unfollow`,
  `unmute`,
  `untag`,
  `viral`,
  `vlog`,
] as const;

export const INFORMAL_WRITING_CONTRACTION_PATTERN =
  /\b[\p{L}]+(?:n't|'d|'ll|'m|'re|'s|'ve)\b/iu;
export const INFORMAL_WRITING_REPEATED_LETTERS_PATTERN = /(\p{L})\1{2,}/iu;
export const INFORMAL_WRITING_CASUAL_PUNCTUATION_PATTERN = /[!?]{2,}/u;
export const INFORMAL_WRITING_EMOTICON_PATTERN = /(?:[:;]-?[)(D])/u;
