export const TEXT_CASING_STYLE_CAMEL_CASE = `CAMEL_CASE`;
export const TEXT_CASING_STYLE_CONSTANT_CASE = `CONSTANT_CASE`;
export const TEXT_CASING_STYLE_EMPTY = `EMPTY`;
export const TEXT_CASING_STYLE_KEBAB_CASE = `KEBAB_CASE`;
export const TEXT_CASING_STYLE_LOWERCASE = `LOWERCASE`;
export const TEXT_CASING_STYLE_MIXED_CASE = `MIXED_CASE`;
export const TEXT_CASING_STYLE_PASCAL_CASE = `PASCAL_CASE`;
export const TEXT_CASING_STYLE_SENTENCE_CASE = `SENTENCE_CASE`;
export const TEXT_CASING_STYLE_SNAKE_CASE = `SNAKE_CASE`;
export const TEXT_CASING_STYLE_TITLE_CASE = `TITLE_CASE`;
export const TEXT_CASING_STYLE_UPPERCASE = `UPPERCASE`;

export const TEXT_CASING_STYLES = [
  TEXT_CASING_STYLE_CAMEL_CASE,
  TEXT_CASING_STYLE_CONSTANT_CASE,
  TEXT_CASING_STYLE_EMPTY,
  TEXT_CASING_STYLE_KEBAB_CASE,
  TEXT_CASING_STYLE_LOWERCASE,
  TEXT_CASING_STYLE_MIXED_CASE,
  TEXT_CASING_STYLE_PASCAL_CASE,
  TEXT_CASING_STYLE_SENTENCE_CASE,
  TEXT_CASING_STYLE_SNAKE_CASE,
  TEXT_CASING_STYLE_TITLE_CASE,
  TEXT_CASING_STYLE_UPPERCASE,
] as const;

export const TEXT_WORD_PATTERN = /\p{L}+/gu;
export const CAMEL_CASE_PATTERN = /^[a-z][a-z0-9]+(?:[A-Z][a-z0-9]+)+$/u;
export const CONSTANT_CASE_PATTERN = /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/u;
export const KEBAB_CASE_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)+$/u;
export const PASCAL_CASE_PATTERN = /^[A-Z][a-z0-9]+(?:[A-Z][a-z0-9]+)+$/u;
export const SNAKE_CASE_PATTERN = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)+$/u;
