export const SSE_TRANSFORM_STREAM_STATUS_DATA = `DATA`;
export const SSE_TRANSFORM_STREAM_STATUS_DONE = `DONE`;
export const SSE_TRANSFORM_STREAM_STATUSES = [
  SSE_TRANSFORM_STREAM_STATUS_DATA,
  SSE_TRANSFORM_STREAM_STATUS_DONE,
] as const;
