export const CHAT_MESSAGE_TEXT_EMPTY_ACTION_ERROR = `error` as const;
export const CHAT_MESSAGE_TEXT_EMPTY_ACTION_INCLUDE = `include` as const;
export const CHAT_MESSAGE_TEXT_EMPTY_ACTION_OMIT = `omit` as const;

export const CHAT_MESSAGE_TEXT_EMPTY_ACTIONS = [
  CHAT_MESSAGE_TEXT_EMPTY_ACTION_ERROR,
  CHAT_MESSAGE_TEXT_EMPTY_ACTION_INCLUDE,
  CHAT_MESSAGE_TEXT_EMPTY_ACTION_OMIT,
] as const;

export const CHAT_MESSAGE_CONTENT_PART_UNSUPPORTED_ACTION_ERROR =
  `error` as const;
export const CHAT_MESSAGE_CONTENT_PART_UNSUPPORTED_ACTION_OMIT =
  `omit` as const;

export const CHAT_MESSAGE_CONTENT_PART_UNSUPPORTED_ACTIONS = [
  CHAT_MESSAGE_CONTENT_PART_UNSUPPORTED_ACTION_ERROR,
  CHAT_MESSAGE_CONTENT_PART_UNSUPPORTED_ACTION_OMIT,
] as const;

export const CHAT_MESSAGE_CONTENT_PART_TYPE_TEXT = `text` as const;

export const CHAT_MESSAGE_TEXT_SEPARATOR = `\n` as const;
export const CHAT_MESSAGE_CONTENT_PART_TEXT_SEPARATOR = `\n` as const;

export const EXTRACT_CHAT_MESSAGE_TEXTS_STATUS_ERROR = `ERROR` as const;
export const EXTRACT_CHAT_MESSAGE_TEXTS_STATUS_SUCCESS = `SUCCESS` as const;
