export const PARSE_JSONL_CONTENT_ISSUE_CODE_BLANK_LINE = `BLANK_LINE` as const;
export const PARSE_JSONL_CONTENT_ISSUE_CODE_INVALID_JSON =
  `INVALID_JSON` as const;

export const PARSE_JSONL_CONTENT_ISSUE_CODES = [
  PARSE_JSONL_CONTENT_ISSUE_CODE_BLANK_LINE,
  PARSE_JSONL_CONTENT_ISSUE_CODE_INVALID_JSON,
] as const;
