export const POINT_OF_VIEW_FIRST_PERSON = `FIRST_PERSON`;
export const POINT_OF_VIEW_MIXED = `MIXED`;
export const POINT_OF_VIEW_SECOND_PERSON = `SECOND_PERSON`;
export const POINT_OF_VIEW_THIRD_PERSON = `THIRD_PERSON`;
export const POINT_OF_VIEW_UNKNOWN = `UNKNOWN`;

export const POINTS_OF_VIEW = [
  POINT_OF_VIEW_FIRST_PERSON,
  POINT_OF_VIEW_MIXED,
  POINT_OF_VIEW_SECOND_PERSON,
  POINT_OF_VIEW_THIRD_PERSON,
  POINT_OF_VIEW_UNKNOWN,
] as const;

/*
 * Pronoun sets are Monorepo-owned curated examples, cross-checked on 2026-06-06
 * against English grammar references and public pronoun guides, including
 * university pronoun guides and common neopronoun reference material. These
 * are not copied third-party tables.
 */
export const FIRST_PERSON_PRONOUNS = [
  `i`,
  `i'd`,
  `i'd've`,
  `i'll`,
  `i'ma`,
  `i'mma`,
  `i'm`,
  `i've`,
  `imma`,
  `let's`,
  `me`,
  `meself`,
  `mine`,
  `my`,
  `myself`,
  `our`,
  `ours`,
  `ourselves`,
  `us`,
  `we`,
  `we'd`,
  `we'd've`,
  `we'll`,
  `we're`,
  `we've`,
] as const;

export const SECOND_PERSON_PRONOUNS = [
  `u`,
  `ur`,
  `ya`,
  `y'all`,
  `y'all'd`,
  `y'all'd've`,
  `y'all'll`,
  `y'all're`,
  `y'all's`,
  `y'all've`,
  `y'alls`,
  `yall`,
  `yall's`,
  `yalls`,
  `ye`,
  `yer`,
  `yins`,
  `yinz`,
  `you`,
  `you-all`,
  `you-uns`,
  `you'd`,
  `you'll`,
  `you'uns`,
  `you're`,
  `you've`,
  `your`,
  `yours`,
  `yourself`,
  `yourselves`,
  `yous`,
  `youse`,
  `yunz`,
] as const;

export const THIRD_PERSON_PRONOUNS = [
  `ae`,
  `aer`,
  `aers`,
  `aerself`,
  `eir`,
  `eirs`,
  `em`,
  `emself`,
  `ey`,
  `fae`,
  `faer`,
  `faers`,
  `faerself`,
  `he`,
  `he'd`,
  `he'll`,
  `he's`,
  `her`,
  `hers`,
  `herself`,
  `hir`,
  `hirs`,
  `hirself`,
  `him`,
  `himself`,
  `his`,
  `it`,
  `it'd`,
  `it'll`,
  `it's`,
  `its`,
  `itself`,
  `ne`,
  `nem`,
  `nemself`,
  `nir`,
  `nirs`,
  `one's`,
  `oneself`,
  `she`,
  `she'd`,
  `she'll`,
  `she's`,
  `their`,
  `theirs`,
  `them`,
  `themself`,
  `themselves`,
  `they`,
  `they'd`,
  `they'll`,
  `they're`,
  `they've`,
  `thon`,
  `thons`,
  `thonself`,
  `ve`,
  `ver`,
  `vers`,
  `verself`,
  `vis`,
  `xe`,
  `xem`,
  `xemself`,
  `xyr`,
  `xyrs`,
  `xyrself`,
  `ze`,
  `zir`,
  `zirs`,
  `zirself`,
  `zhe`,
  `zher`,
  `zhers`,
  `zherself`,
] as const;
