export const OBFUSCATION_SIGNAL_LEETSPEAK = `LEETSPEAK`;
export const OBFUSCATION_SIGNAL_SPACED_WORD = `SPACED_WORD`;
export const OBFUSCATION_SIGNAL_SYMBOL_SUBSTITUTION = `SYMBOL_SUBSTITUTION`;
export const OBFUSCATION_SIGNAL_ZERO_WIDTH = `ZERO_WIDTH`;

export const OBFUSCATION_SIGNALS = [
  OBFUSCATION_SIGNAL_LEETSPEAK,
  OBFUSCATION_SIGNAL_SPACED_WORD,
  OBFUSCATION_SIGNAL_SYMBOL_SUBSTITUTION,
  OBFUSCATION_SIGNAL_ZERO_WIDTH,
] as const;

export const LEETSPEAK_LETTER_PATTERN = /[a-z]/iu;
export const LEETSPEAK_DIGIT_PATTERN = /\d/u;
export const SYMBOL_SUBSTITUTION_PATTERN = /[\w][@$+!][\w]/u;
export const SPACED_WORD_PATTERN = /(?:\b[\p{L}]\s+){2,}[\p{L}]\b/iu;
export const ZERO_WIDTH_PATTERN = /[\u200B-\u200D\uFEFF]/u;
