export const DEFAULT_HTTP_MAX_ATTEMPTS = 3;
export const DEFAULT_HTTP_MAX_RETRY_DELAY_MS = 30_000;
export const DEFAULT_HTTP_REQUEST_LABEL = `HTTP request`;
export const DEFAULT_HTTP_RETRY_DELAY_JITTER = true;
export const DEFAULT_HTTP_RETRY_DELAY_MS = 1_000;
export const DEFAULT_HTTP_RETRY_DELAY_MULTIPLIER = 2;
export const HTTP_METHOD_GET = `get`;
export const HTTP_METHOD_POST = `post`;
export const HTTP_METHOD_PUT = `put`;
export const HTTP_METHOD_PATCH = `patch`;
export const HTTP_METHOD_HEAD = `head`;
export const HTTP_METHOD_DELETE = `delete`;
export const HTTP_METHOD_OPTIONS = `options`;
export const HTTP_METHOD_TRACE = `trace`;
export const DEFAULT_HTTP_RETRY_METHODS = [
  HTTP_METHOD_GET,
  HTTP_METHOD_POST,
  HTTP_METHOD_PUT,
  HTTP_METHOD_PATCH,
  HTTP_METHOD_HEAD,
  HTTP_METHOD_DELETE,
  HTTP_METHOD_OPTIONS,
  HTTP_METHOD_TRACE,
] as const;
export const DEFAULT_HTTP_TIMEOUT_MS = 60_000;
export const HTTP_MIN_MAX_ATTEMPTS = 1;
export const HTTP_MIN_RESPONSE_BODY_SNIPPET_LENGTH = 0;
export const HTTP_MIN_RETRY_DELAY_MS = 0;
export const HTTP_MIN_RETRY_DELAY_MULTIPLIER = 1;
export const HTTP_MIN_TIMEOUT_MS = 1;
export const HTTP_HEADER_CONTENT_TYPE = `content-type`;
export const HTTP_CONTENT_TYPE_JSON = `application/json`;
export const HTTP_RESPONSE_BODY_SNIPPET_LENGTH = 2_000;
export const HTTP_STATUS_MIN = 100;
export const HTTP_STATUS_MAX = 599;
export const HTTP_STATUS_REQUEST_TIMEOUT = 408;
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_TOO_EARLY = 425;
export const HTTP_STATUS_TOO_MANY_REQUESTS = 429;
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
export const HTTP_STATUS_BAD_GATEWAY = 502;
export const HTTP_STATUS_SERVICE_UNAVAILABLE = 503;
export const HTTP_STATUS_GATEWAY_TIMEOUT = 504;

export const DEFAULT_HTTP_RETRYABLE_STATUSES = [
  HTTP_STATUS_REQUEST_TIMEOUT,
  HTTP_STATUS_CONFLICT,
  HTTP_STATUS_TOO_EARLY,
  HTTP_STATUS_TOO_MANY_REQUESTS,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
  HTTP_STATUS_BAD_GATEWAY,
  HTTP_STATUS_SERVICE_UNAVAILABLE,
  HTTP_STATUS_GATEWAY_TIMEOUT,
] as const;
