export const PACKAGES_DIRECTORY_NAME = `packages`;
export const PACKAGE_JSON_FILE_NAME = `package.json`;

export const PACKAGE_DIRECTORY_IGNORED_NAME_NODE_MODULES = `node_modules`;
export const PACKAGE_DIRECTORY_IGNORED_NAME_TURBO = `.turbo`;
export const PACKAGE_DIRECTORY_IGNORED_NAME_DS_STORE = `.DS_Store`;

export const PACKAGE_DIRECTORY_IGNORED_NAMES = [
  PACKAGE_DIRECTORY_IGNORED_NAME_NODE_MODULES,
  PACKAGE_DIRECTORY_IGNORED_NAME_TURBO,
  PACKAGE_DIRECTORY_IGNORED_NAME_DS_STORE,
] as const;

export const PATHS_RESULT_STATUS_SUCCESS = `SUCCESS`;
export const PATHS_RESULT_STATUS_ERROR = `ERROR`;

export const PATHS_RESULT_STATUSES = [
  PATHS_RESULT_STATUS_SUCCESS,
  PATHS_RESULT_STATUS_ERROR,
] as const;
